# ======================================================
# choharutwo.dk - choharu2 메인 (로컬 개발용 HTTP)
# ======================================================
server {
    listen 80;
    server_name choharutwo.dk www.choharutwo.dk;
    root /var/www/choharu2/site/saju/main;

    client_max_body_size 32M;
    index index.php;

    location / {
        if (!-f $request_filename) {
            rewrite ^ /index.php/$1 last;
        }
        try_files $uri $uri/ =404;
    }

    location /index.php {
        fastcgi_intercept_errors on;
        fastcgi_pass php74:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param SCRIPT_NAME $fastcgi_script_name;
    }

    location ~ \.(php|html|htm)$ {
        fastcgi_intercept_errors on;
        fastcgi_pass php74:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param SCRIPT_NAME $fastcgi_script_name;
    }

    location ~ /data/([a-zA-Z0-9_]+)/([a-zA-Z0-9_]+)/([a-zA-Z0-9_]+)/([a-zA-Z0-9_]+)\.(php|html|htm)$ {
        return 403;
    }

    location ~ /data/([a-zA-Z0-9_]+)/([a-zA-Z0-9_]+)/([a-zA-Z0-9_]+)/([a-zA-Z0-9_]+)([^\.])$ {
        return 403;
    }

    error_log /var/log/nginx/choharutwo-error.log;
    access_log /var/log/nginx/choharutwo-access.log;
}


# ======================================================
# admin.choharutwo.dk - choharu2 어드민 (로컬 개발용 HTTP)
# ======================================================
server {
    listen 80;
    server_name admin.choharutwo.dk;
    root /var/www/choharu2/site/saju/admin/public;

    client_max_body_size 32M;
    index index.php;

    location / {
        if (!-f $request_filename) {
            rewrite ^ /index.php/$1 last;
        }
        try_files $uri $uri/ =404;
    }

    location /index.php {
        fastcgi_intercept_errors on;
        fastcgi_pass php74:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param SCRIPT_NAME $fastcgi_script_name;
    }

    location ~ \.(php|html|htm)$ {
        fastcgi_intercept_errors on;
        fastcgi_pass php74:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param SCRIPT_NAME $fastcgi_script_name;
    }

    error_log /var/log/nginx/admin-choharutwo-error.log;
    access_log /var/log/nginx/admin-choharutwo-access.log;
}
