# ======================================================
# Apache 프록시 - customsg / withus 도메인
# ======================================================

# customsgCRM
server {
    listen 80;
    server_name emp.custom-message.dk www.emp.custom-message.dk;
    location / {
        proxy_pass http://local_apache:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

# customsgPTN
server {
    listen 80;
    server_name ptn.custom-message.dk www.ptn.custom-message.dk;
    location / {
        proxy_pass http://local_apache:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

# customsgLANDING
server {
    listen 80;
    server_name land.custom-message.dk www.land.custom-message.dk;
    location / {
        proxy_pass http://local_apache:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

# customsgLANDING file
server {
    listen 80;
    server_name file.custom-message.dk www.file.custom-message.dk;
    location / {
        proxy_pass http://local_apache:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

# customsgnews
server {
    listen 80;
    server_name customsgnews.dk www.customsgnews.dk;
    location / {
        proxy_pass http://local_apache:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

# withusCRM
server {
    listen 80;
    server_name emp.withusmk.dk www.emp.withusmk.dk;
    location / {
        proxy_pass http://local_apache:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

# withusPTN
server {
    listen 80;
    server_name ptn.withusmk.dk www.ptn.withusmk.dk;
    location / {
        proxy_pass http://local_apache:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

# withusLanding
server {
    listen 80;
    server_name land.withusmk.dk www.land.withusmk.dk;
    location / {
        proxy_pass http://local_apache:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

# withusFile
server {
    listen 80;
    server_name file.withusmk.dk www.file.withusmk.dk;
    location / {
        proxy_pass http://local_apache:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

# withusnews
server {
    listen 80;
    server_name withusnews.dk www.withusnews.dk;
    location / {
        proxy_pass http://local_apache:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
