zend_extension=xdebug

[xdebug]
xdebug.mode=debug
xdebug.start_with_request=yes
; Docker에서 호스트(Windows/Mac) 접근 시 host.docker.internal 사용
xdebug.client_host=192.168.65.254
xdebug.client_port=9003
xdebug.log=/tmp/xdebug.log
